---
title: "A2 Eric"
output: html_document
date: "2022-11-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# load libraries 

```{r}
library(tidyverse)
library(mgcv)
library(xgboost)
library(missForest)
library(doParallel)
library(cesR)
library(caret)
library(randomForest)
library(GGally)
registerDoParallel(cores=24)
```

# load in finished datasets 

```{r}
set.seed(123)
predictors_all <- read_csv("ces2019_web_all_predictors.csv") %>% mutate_if(is.character, as.factor) %>% select(-c(income_number)) %>% mutate(vote_choice = as.factor(vote_choice)) %>% as.data.frame()
predictors_reduced <- read_csv("ces2019_web_reduced_predictors.csv") %>% mutate_if(is.character, as.factor) %>% mutate(vote_choice = as.factor(vote_choice)) %>% as.data.frame()

train_full <- predictors_all %>% sample_frac(0.8)
test_full <- predictors_all %>% anti_join(predictors_all, by = "cps19_ResponseId")

train_full <- train_full %>% select(-c(cps19_ResponseId))
test_full <- test_full %>% select(-c(cps19_ResponseId))


train_reduced <- predictors_reduced %>% sample_frac(0.8)
test_reduced <- predictors_reduced %>% anti_join(predictors_reduced, by = "cps19_ResponseId")

train_reduced <- train_reduced %>% select(-c(cps19_ResponseId))
test_reduced <- test_reduced %>% select(-c(cps19_ResponseId))

glimpse(train_full)
glimpse(train_reduced)
```

# data exploration 

## perform feature selection 
```{r}
set.seed(123)
# use recursive feature selection 
predictors <- train_full %>% select(-c(vote_choice))
output <- train_full %>% select(vote_choice)
rfe_control <- rfeControl(
                      functions = rfFuncs,
                      method = "repeatedcv",
                      repeats = 5,
                      number = 5)
rfe_predictors <- rfe(x = predictors[, 1:ncol(predictors)], y = output[, 1], sizes = c(1:ncol(predictors)), rfeControl = rfe_control)

```

```{r}
rfe_predictors
predictors(rfe_predictors)
```

# model tests

```{r}
library(GGally)
ggpairs(predictors_full_no_na %>% select(c(liberal_favour, conservative_favour, ndp_favour, bloc_favour, green_favour, vote_choice)))
```

## GAM full model

```{r}
library(parallel)
train_full <- train_full %>% mutate(vote_choice = as.numeric(as.character(vote_choice)))
test_full <- test_full %>% mutate(vote_choice = as.numeric(as.character(vote_choice)))


test_gam <- mgcv::gam(list(vote_choice ~ s(liberal_favour), 
                           ~ s(liberal_favour), 
                           ~ s(liberal_favour),
                           ~ s(liberal_favour),
                           ~ s(liberal_favour)),
                      data = train_full, 
                      family = multinom(K=5), 
                      method = "REML",
                      control = mgcv::gam.control(nthreads= 24))


ran_effects.full <- mgcv::gam(data = train_full, formula = 
                         list(
                           vote_choice ~ s(province, bs="re") + s(health, bs = "re") +s(age_category, bs = "re") + s(education, bs = "re") + s(income_category, bs="re") + s(marital_status, bs = "re") + s(language, bs = "re") + s(gender, bs = "re") + s(owns_house, bs = "re") + s(born_in_canada, bs = "re") + s(citizenship, bs="re"), 
                           ~ s(province, bs="re") + s(health, bs = "re") +s(age_category, bs = "re") + s(education, bs = "re") + s(income_category, bs="re") + s(marital_status, bs = "re") + s(language, bs = "re") + s(gender, bs = "re") + s(owns_house, bs = "re") + s(born_in_canada, bs = "re") + s(citizenship, bs="re"), 
                           ~ s(province, bs="re") + s(health, bs = "re") +s(age_category, bs = "re") + s(education, bs = "re") + s(income_category, bs="re") + s(marital_status, bs = "fs") + s(language, bs = "re") + s(gender, bs = "re") + s(owns_house, bs = "re") + s(born_in_canada, bs = "re") + s(citizenship, bs="re"),
                           ~ s(province, bs="re") + s(health, bs = "re") +s(age_category, bs = "re") + s(education, bs = "re") + s(income_category, bs="re") + s(marital_status, bs = "re") + s(language, bs = "re") + s(gender, bs = "re") + s(owns_house, bs = "re") + s(born_in_canada, bs = "re") + s(citizenship, bs="re"),
                           ~ s(province, bs="re") + s(health, bs = "re") +s(age_category, bs = "re") + s(education, bs = "re") + s(income_category, bs="re") + s(marital_status, bs = "re") + s(language, bs = "re") + s(gender, bs = "re") + s(owns_house, bs = "re") + s(born_in_canada, bs = "re") + s(citizenship, bs="re")
                        ), 
                       family = mgcv::multinom(K=5),  
                       method="REML")
summary(ran_effects_gam_model)

plot(ran_effects.full, pages = 1, trans = plogis,
     shift = coef(ran_effects.full)[1], seWithMean = TRUE)

# random intercepts only 
mixed_effects.full <- mgcv::gam(data = train_full, 
                                         formula = list(
                                           vote_choice ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps") + s(province, bs="re") + s(health, bs = "re") +s(age_category, bs = "re") + s(education, bs = "re") + s(income_category, bs="re") + s(marital_status, bs = "re") + s(language, bs = "re") + s(gender, bs = "re") + s(owns_house, bs = "re") + s(born_in_canada, bs = "re") + s(citizenship, bs="re"),
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps") + s(province, bs="re") + s(health, bs = "re") +s(age_category, bs = "re") + s(education, bs = "re") + s(income_category, bs="re") + s(marital_status, bs = "re") + s(language, bs = "re") + s(gender, bs = "re") + s(owns_house, bs = "re") + s(born_in_canada, bs = "re") + s(citizenship, bs="re"),
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps") + s(province, bs="re") + s(health, bs = "re") +s(age_category, bs = "re") + s(education, bs = "re") + s(income_category, bs="re") + s(marital_status, bs = "re") + s(language, bs = "re") + s(gender, bs = "re") + s(owns_house, bs = "re") + s(born_in_canada, bs = "re") + s(citizenship, bs="re"),
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps") + s(province, bs="re") + s(health, bs = "re") +s(age_category, bs = "re") + s(education, bs = "re") + s(income_category, bs="re") + s(marital_status, bs = "re") + s(language, bs = "re") + s(gender, bs = "re") + s(owns_house, bs = "re") + s(born_in_canada, bs = "re") + s(citizenship, bs="re"),
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps") + s(province, bs="re") + s(health, bs = "re") +s(age_category, bs = "re") + s(education, bs = "re") + s(income_category, bs="re") + s(marital_status, bs = "re") + s(language, bs = "re") + s(gender, bs = "re") + s(owns_house, bs = "re") + s(born_in_canada, bs = "re") + s(citizenship, bs="re")
                                         ), 
                                         family = mgcv::multinom(K=5), 
                                         method = "REML")

# fixed effects only 
fixed_effects.full <- mgcv::gam(data = train_full, 
                                         formula = list(
                                           vote_choice ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps"),
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps"),
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps"),
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps"),
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps")
                                         ), 
                                         family = mgcv::multinom(K=5))

```

### Full model test values 

```{r}

```

## Reduced Complexity Model 

```{r}
train_reduced <- train_reduced %>% mutate(vote_choice = as.numeric(as.character(vote_choice)))
test_reduced <- test_reduced %>% mutate(vote_choice = as.numeric(as.character(vote_choice)))

# random effects only 
ran_effects.reduced <- mgcv::gam(data = train_reduced, formula = 
                         list(
                           vote_choice ~ s(province, bs="re") + s(language, bs = "re"), 
                           ~ s(province, bs="re") + s(language, bs = "re"), 
                           ~ s(province, bs="re") + s(language, bs = "re"),
                           ~ s(province, bs="re") + s(language, bs = "re"),
                           ~ s(province, bs="re") + s(language, bs = "re")
                        ), 
                       family = mgcv::multinom(K=5),  
                       method="REML")
summary(ran_effects_gam_model)

plot(ran_effects.reduced, pages = 1, trans = plogis,
     shift = coef(ran_effects.reduced)[1], seWithMean = TRUE)

# mixed effects model
mixed_effects.reduced <- mgcv::gam(data = train_reduced, 
                                         formula = list(
                                           vote_choice ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps") + s(province, bs = "re") + s(language, bs = "re"),
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps") + s(province, bs = "re") + s(language, bs = "re"),
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps") + s(province, bs = "re") + s(language, bs = "re"),
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps") + s(province, bs = "re") + s(language, bs = "re"),
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps") + s(province, bs = "re") + s(language, bs = "re")
                                         ), 
                                         family = mgcv::multinom(K=5), 
                                         method = "REML")
# fixed effects model
fixed_effects.reduced <- mgcv::gam(data = train_reduced, 
                                         formula = list(
                                           vote_choice ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps") ,
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps"),
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps"),
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps"),
                                           ~ s(liberal_favour, bs="ps") + s(conservative_favour, bs="ps") + s(ndp_favour, bs="ps") + s(green_favour, bs="ps") + s(people_favour, bs="ps") + s(bloc_favour, bs="ps")
                                         ), 
                                         family = mgcv::multinom(K=5))
```

```{r}
ran_effects.reduced.predictions <- predict(ran_effects.reduced, type="class", newdata = test_reduced)

```
  